# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: index.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bindex.proto\x12\ttachiyomi\"6\n\nExtensions\x12(\n\nextensions\x18\x01 \x03(\x0b\x32\x14.tachiyomi.Extension\"\xbb\x01\n\tExtension\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pkg\x18\x02 \x01(\t\x12\x0b\n\x03\x61pk\x18\x03 \x01(\t\x12\x0c\n\x04lang\x18\x04 \x01(\t\x12\x0c\n\x04\x63ode\x18\x05 \x01(\x05\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x0c\n\x04nsfw\x18\x07 \x01(\x05\x12\x11\n\thasReadme\x18\x08 \x01(\x08\x12\x14\n\x0chasChangelog\x18\t \x01(\x08\x12\"\n\x07sources\x18\n \x03(\x0b\x32\x11.tachiyomi.Source\"\xa6\x02\n\x06Source\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x03\x12\x0f\n\x07\x62\x61seUrl\x18\x04 \x01(\t\x12\x11\n\tversionId\x18\x05 \x01(\x05\x12\x0c\n\x04nsfw\x18\x06 \x01(\x05\x12\x0b\n\x03\x61pp\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\x05\x12\x0b\n\x03pkg\x18\t \x01(\t\x12\x0f\n\x07version\x18\n \x01(\t\x12\x11\n\thasReadme\x18\x0b \x01(\x08\x12\x14\n\x0chasChangelog\x18\x0c \x01(\x08\x12\x0f\n\x07iconUrl\x18\r \x01(\t\x12\x17\n\x0fminMihonVersion\x18\x0e \x01(\t\x12\x17\n\x0fmaxMihonVersion\x18\x0f \x01(\t\x12\x1d\n\x15signingKeyFingerprint\x18\x10 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTENSIONS']._serialized_start=26
  _globals['_EXTENSIONS']._serialized_end=80
  _globals['_EXTENSION']._serialized_start=83
  _globals['_EXTENSION']._serialized_end=270
  _globals['_SOURCE']._serialized_start=273
  _globals['_SOURCE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
